# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    google:
        enabled: true
        issuer: 'wsbSecurityProject'
        server_name: 'wsbSecurity'
        digits: 6
#        template: 'security/2fa_form.html.twig' # Ścieżka do szablonu jakbym chciał zmienić front
